controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: POST|PUT

app_homepage:
    path: /
    controller: App\Controller\HomepageController::index
